# This is a generated file. Not intended for manual editing.
services:
  simpleapp:
    build:
      context: "D:\\workspace\\DemoBFF\\backend\\SimpleApp"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "simpleapp:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:51828:57300"
    volumes:
    - "C:\\Users\\admin\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\workspace\\DemoBFF\\backend\\SimpleApp:/app:rw"
    - "D:\\workspace\\DemoBFF\\backend:/src:rw"
    - "C:\\Users\\admin\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\admin\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_6_18_11_29_46:/var/opt/rider-debugger:rw"
    working_dir: "/app"
